### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by fiskhest** [pvelati/ansible-role-proxmox-kvm-mgmt#4]
I stumbled upon this project and wanted to take it for a spin. I'm reading the `USAGE` sub-chapter of the README, but I'm not at all understanding how to get rolling.

```
Define a list of virtual machines in this format:
vm_list:
   - name: vm1
     net: {"net0":"virtio=32:5F:B4:35:16:0F,bridge=vmbr0"}
     scsi: {"scsi0":"local-lvm:8,ssd=1"}
     cores: 1
     memory: 1024
     balloon: 512
     vga: vmware
   - name: vm2
     net: {"net0":"virtio=32:5F:B4:37:16:0F,bridge=vmbr1"}
     scsi: {"scsi0":"local-lvm:16,ssd=1"}
     cores: 4
     memory: 4096
     protection: yes
```
```
Execute playbook:
ansible-playbook ansible-proxmox-kvm-mgmt.yml --tags "OPERATION"
```

The first list of dicts isn't an ansible playbook, and the `ansible-proxmox-kvm-mgmt.yml` playbook does not exist in the repo. Am I completely overseeing something here or is there something missing from the readme?

**Comment by fiskhest** [comment]
I just noticed an example playbook when scrolling further down, but it isn't really sufficient either:

```
---
- hosts: localhost  
  roles:
    - ansible-proxmox-kvm-mgmt
  vars:
    - global_api_host: "x.y.z.i"
    - global_node: "some-pve-node-name"
```

```
❯ ansible-playbook ansible-proxmox-kvm-mgmt.yml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match
'all'
ERROR! the role 'ansible-proxmox-kvm-mgmt' was not found in /home/user/Documents/work/company/proxmox_migration/ansible-role-proxmox-kvm-mgmt/roles:/home/user/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/user/Documents/work/company/proxmox_migration/ansible-role-proxmox-kvm-mgmt

The error appears to be in '/home/user/Documents/work/company/proxmox_migration/ansible-role-proxmox-kvm-mgmt/ansible-proxmox-kvm-mgmt.yml': line 4, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - ansible-proxmox-kvm-mgmt
      ^ here
```

**Comment by pvelati** [comment]
Hello @fiskhest , I've just updated the role.
This role is not a standalone, but something you should put in the roles directory

```
- playbook.yaml
- roles
- roles/ansible-proxmox-kvm-mgmt
- group_vars ..... and so on
```
check this for the directory layout: https://docs.ansible.com/ansible/2.3/playbooks_best_practices.html#directory-layout

For this role you can use it with a playbook like this:

```
---
- hosts: localhost
  roles:
    - ansible-proxmox-kvm-mgmt
  collections:
    - community.general.proxmox_kvm
  vars:
    - global_api_host: "x.y.z.i"
    - global_node: "some-pve-node-name"
    - vm_list:
        - name: example-vm1
          net: {"net0":"virtio=32:5F:B4:35:16:0F,bridge=vmbr0"}
          scsi: {"scsi0":"ssd:8,ssd=1"}
          bootdisk: 'scsi0'
        - name: example-vm2
          net: {"net0":"virtio=32:B4:5F:16:35:0F,bridge=vmbr1"}
          scsi: {"scsi0":"ssd:20,ssd=1"}
          bootdisk: 'scsi0'
```

You can also edit the vm_list in the group_vars if you prefer.
From now on there will not be any default variable set for some parameters (acpi, autostart, balloon, boot, cores, cpu, cpuunits, force, format, kvm, memory, onboot, ostype, sockets, tablet, template, vga) as stated here: https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_kvm_module.html#parameter-proxmox_default_behavior.
